### ISSUE TITLE
BIDS validation

### ISSUE THREAD

**Issue by N-HEDGER** [N-HEDGER/NEURO_PYTHON#6]
It would be good to include a 'validate' method in the BIDS class.

This would be the first thing to call after the _init_ function.

This performs sanity checks to determine whether there is some.

There is probably some existing code out there that this can be based on.

**Comment by eroesch** [comment]
https://pypi.org/project/bids-validator/

**Comment by bwilliams96** [comment]
BIDS validation method created, see 61e3752ea00adc31a1c37a59672aa2394b2b6b9a (didn't close issue with commit)

**Comment by N-HEDGER** [comment]
@bwilliams96 Could you let me know the exact version of the BIDs validator you are using?

**Comment by bwilliams96** [comment]
@N-HEDGER bids-validator 1.5.7
